---
title: '#30DayChartChallenge'
subtitle: 'Day 5 - Slope'
author: "Moriah Taylor"
date: "4/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Data - Greenhouse Gas Emissions

This data on greenhouse gas emissions comes from Our World in Data. I figured what better way to show slope in an impactful way than with emissions data.

```{r, message=FALSE, warning=FALSE, include=TRUE}
#load packages
library(tidyverse)
library(lubridate)
library(extrafont)
library(showtext)
library(rmarkdown)
library(graphics)
library(ggdark)
library(ragg)
library(ggimage)
library(RColorBrewer)
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#read in data
emissions <- read.csv('emissions_clean.csv')
#separate the aggregated data, as well as US, China, and India
groups <- c('Africa', 'Asia', 'Asia (excl. China & India)', 'Australia', 'China', 'Europe', 'India', 'North America', 
            'North America (excl. USA)', 'Oceania', 'South America', 'United States', 'World')
emissions_agg <- subset(emissions, country %in% groups)
#get years for co2 graph
co2_years <- c(2000,2019)
#co2 subset
co2_emissions <- subset(emissions, year %in% co2_years)

#get years for co2, methane, nitrous oxide, total ghg visuals
ghg_years <- c(2000, 2016)
ghg_emissions <- subset(emissions, year %in% ghg_years)
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#add custom text
font_add(family = "title", "PatuaOne-Regular.ttf")
font_add(family = "subtitle", "Cantarell-Italic.ttf")
font_add(family = "caption", "Merriweather-Regular.ttf")
showtext.auto()

#create themes
plot_theme <- theme(
  # titles
  plot.title = element_text(family = "title", size = 45, color = "#525353", hjust=0, vjust=0),
  plot.subtitle = element_text(family = "subtitle", size = 35, color = "black", hjust=0, vjust=0),
  plot.caption = element_text(family = "caption", size = 20, color = "#525353", hjust = 1),
  
  # panel and plot background
  panel.grid.minor = element_line(color="#d6d6d6"),
  panel.grid.major = element_line(color="#d6d6d6"),
  panel.background = element_rect(fill = "#cccccc"),
  plot.background = element_rect(fill = "#cccccc"),
  
  # axis
  axis.title = element_text(family="caption", size=35, color="black"),
  axis.text = element_text(family="caption", size=25, color="black"),
  axis.ticks = element_blank(),
  
  #legend
  legend.title = element_text(family="caption", size=20, color="black"),
  legend.text = element_text(family = "caption", size=20, color="black"),
  legend.background = element_rect(fill="white", size=0.5, linetype="solid", color="black")
)

plot_theme2 <- theme(
  # titles
  plot.title = element_text(family = "title", size = 45, color = "#525353", hjust=0, vjust=0),
  plot.subtitle = element_text(family = "subtitle", size = 35, color = "black", hjust=0, vjust=0),
  plot.caption = element_text(family = "caption", size = 20, color = "#525353", hjust = 1),
  
  # panel and plot background
  panel.grid.minor = element_line(color="#d6d6d6"),
  panel.grid.major = element_line(color="#d6d6d6"),
  panel.background = element_rect(fill = "#ffffff"),
  plot.background = element_rect(fill = "#ffffff"),
  
  # axis
  axis.title = element_text(family="caption", size=35, color="black"),
  axis.text = element_text(family="caption", size=25, color="black"),
  axis.ticks = element_blank(),
  
  #legend
  legend.title = element_text(family="caption", size=20, color="black"),
  legend.text = element_text(family = "caption", size=20, color="black"),
  legend.background = element_rect(fill="white", size=0.5, linetype="solid", color="black")
)

mypalette <- c("#7154b1", "#b15481", "#94b154", "#54b19f", "#5485B1", "#801046", "#07438C", "#0C7217")
cbfriendlypalette <- c("#E69f00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", 
                                "#CC79A7", "#628CA5", "#A887CF")
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#co2 plot of regions
regions <- c('Africa', 'Asia', 'Australia', 'Europe', 'North America', 'Oceania', 'South America')
co2_regions <- subset(co2_emissions, country %in% regions)

co2_plot_regions <- ggplot(co2_regions, aes(x=year, y=co2)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Region", values = mypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2019),
                     labels = c("2000", "2019")) +
  #title, subtitle, and caption
  labs(
    title = "CO2 Emissions by Region [2000 vs. 2019]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme

ggsave("co2_plot_regions.png",
       plot = co2_plot_regions,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

#cb-friendly co2 plot
co2_plot_regions_cb <- ggplot(co2_regions, aes(x=year, y=co2)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Region", values = cbfriendlypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2019),
                     labels = c("2000", "2019")) +
  #title, subtitle, and caption
  labs(
    title = "CO2 Emissions by Region [2000 vs. 2019]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme2

ggsave("co2_plot_regions_cb.png",
       plot = co2_plot_regions_cb,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
standout_countries <- c('Asia (excl. China & India)', 'China', 'Europe', 'India', 'North America (excl. USA)', 
               'South America', 'United States')
standouts <- subset(co2_emissions, country %in% standout_countries)

co2_standouts <- ggplot(standouts, aes(x=year, y=co2)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country/Region", values = mypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2019),
                     labels = c("2000", "2019")) +
  #title, subtitle, and caption
  labs(
    title = "CO2 Emissions - Comparing Regions and Countries [2000 vs. 2019]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme

ggsave("co2_standouts_plot.png",
       plot = co2_standouts,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

co2_standouts_cb <- ggplot(standouts, aes(x=year, y=co2)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country/Region", values = cbfriendlypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2019),
                     labels = c("2000", "2019")) +
  #title, subtitle, and caption
  labs(
    title = "CO2 Emissions - Comparing Regions and Countries [2000 vs. 2019]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme2

ggsave("co2_standouts_plot_cb.png",
       plot = co2_standouts_cb,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#all ghg subset
countries <- c('Australia', 'China', 'India', 'United States')
ghg_countries <- subset(ghg_emissions, country %in% countries)

#methane plot
methane_plot <- ggplot(ghg_countries, aes(x=year, y=methane)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = mypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Methane Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme

ggsave("methane_plot.png",
       plot = methane_plot,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

#cb-friendly methane plot
methane_plot_cb <- ggplot(ghg_countries, aes(x=year, y=methane)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = cbfriendlypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Methane Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme2

ggsave("methane_plot_cb.png",
       plot = methane_plot_cb,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#nitrous oxide plot
nitrous_oxide_plot <- ggplot(ghg_countries, aes(x=year, y=nitrous_oxide)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = mypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Nitrous Oxide Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme

ggsave("nitrous_oxide_plot.png",
       plot = nitrous_oxide_plot,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

#cb-friendly nitrous_oxide plot
nitrous_oxide_plot_cb <- ggplot(ghg_countries, aes(x=year, y=nitrous_oxide)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = cbfriendlypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Nitrous Oxide Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme2

ggsave("nitrous_oxide_plot_cb.png",
       plot = nitrous_oxide_plot_cb,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#total_ghg plot
total_ghg_plot <- ggplot(ghg_countries, aes(x=year, y=total_ghg)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = mypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Total GHG Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme

ggsave("total_ghg_plot.png",
       plot = total_ghg_plot,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))

#cb-friendly total_ghg plot
total_ghg_plot_cb <- ggplot(ghg_countries, aes(x=year, y=total_ghg)) + geom_point(aes(color=factor(country))) +
  geom_line(aes(color=factor(country)), size=1) + scale_color_manual(name="Country", values = cbfriendlypalette) + 
  #x scale
  scale_x_continuous(breaks = c(2000,2016),
                     labels = c("2000", "2016")) +
  #title, subtitle, and caption
  labs(
    title = "Total GHG Emissions [2000 vs. 2016]",
    caption = "Source - Our World in Data | Moriah Taylor | Twitter - moriah_taylor58 | GitHub - moriahtaylor1") + 
  xlab("") + ylab("Million Tonnes of CO2") + plot_theme2

ggsave("total_ghg_plot_cb.png",
       plot = total_ghg_plot_cb,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
```