---
title: "#30DayChartChallenge"
subtitle: "Day2 - Pictogram"
author: "Moriah Taylor"
date: "4/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Data - Video Game Players on Steam

Didn't get to do Week 12 of #TidyTuesday so I figured I'd finally put that Steam data to use (can be found here: https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-03-16)

```{r, message=FALSE, warning=FALSE, include=TRUE}
library(tidytuesdayR)
library(tidyverse)
library(lubridate)
library(extrafont)
library(showtext)
library(rmarkdown)
library(png)
library(ggdark)
library(ragg)
library(ggimage)
library(magick)
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#load data
tuesdata <- tidytuesdayR::tt_load('2021-03-16')
games <- tuesdata$games
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#get all games played in April 2020 filtered by average no. of players
lockdown_games <- games %>%
  filter(year == 2020) %>%
  filter(month == "April") %>%
  arrange(desc(avg))

#get top 10 games
top_lockdown_games = lockdown_games[1:10, ]
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
#add custom text
font_add(family = "gamer", "PressStart2P-Regular.ttf")
font_add(family = "quicksand", "Quicksand.ttf")
font_add(family = "concert", "ConcertOne-Regular.ttf")
showtext.auto()

#create labels
thousands <- round(top_lockdown_games$avg/1000, 1)
labelings <- paste(thousands, "K", sep="")

#create dataframe
df <- data.frame(game = top_lockdown_games$gamename,
                 avg_players = top_lockdown_games$avg,
                 lbls = labelings)

#create theme
plot_theme <- theme(
  # titles
  plot.title = element_text(family = "gamer", size = 50, color = "#8aff09", hjust=1),
  plot.subtitle = element_text(family = "quicksand", size = 30, color = "white", hjust = 1),
  plot.caption = element_text(family = "quicksand", size = 28, color = "white", hjust = 0.5),
  
  # panel and plot background
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_rect(fill = "black"),
  plot.background = element_rect(fill = "black"),
  
  # axis
  axis.title = element_blank(),
  axis.text.y = element_text(family="concert", size=25, color="white"),
  axis.text.x = element_blank(),
  axis.ticks = element_blank(),
)

games_plot <- ggplot(df, aes(x=game, y=avg_players)) +
  coord_flip() + geom_bar(stat="identity", fill="#000000") + geom_point(color="white") + 
  geom_text(data = df, nudge_y = 50000, aes(x=game, y=avg_players, label=lbls), family="concert", size=10, 
            color = "white") +
  #title, subtitle, and caption
  labs(
    title = "TOP LOCKDOWN GAMES",
    subtitle = "average number of players at any given time during the COVID lockdown in April 2020",
    caption = "Source: Steam | Moriah Taylor | Twitter: moriah_taylor58 | GitHub: moriahtaylor1") + 
  xlab("") + ylab("") + plot_theme
      
games_plot
```

```{r, message=FALSE, warning=FALSE, include=TRUE}
ggsave("games_plot_unfinished.png",
       plot = games_plot,
       device = agg_png(width = 7, height = 5, units = "in", res = 300))
```

```{r, message=FALSE, warning=FALSE, include=TRUE}

```

```{r, message=FALSE, warning=FALSE, include=TRUE}

```

```{r, message=FALSE, warning=FALSE, include=TRUE}

```

